{{- if .Values.mcpServer.enabled }}
{{- if .Values.mcpServer.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "mcp-server" .Values.mcpServer.serviceAccount.name }}
  labels:
    {{- include "kguardian.labels" . | nindent 4 }}
  {{- with .Values.mcpServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.mcpServer.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
