{{- if .Values.llmBridge.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.llmBridge.service.name }}
  labels:
    {{- include "kguardian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmBridge.service.type }}
  ports:
    - port: {{ .Values.llmBridge.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.llmBridge.service.name }}
{{- end }}
