{{- if .Values.llmBridge.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "llm-bridge" .Values.llmBridge.serviceAccount.name }}
  labels:
    {{- include "kguardian.labels" . | nindent 4 }}
  {{- with .Values.llmBridge.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.llmBridge.serviceAccount.automountServiceAccountToken }}
{{- end }}
