---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Charts: Update README"

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/charts-readme-docs.yaml'
      - 'charts/**'

env:
  HELM_DOCS_VERSION: 1.11.2

jobs:
  chart-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_Linux_x86_64.tar.gz
          tar -xvf helm-docs_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: run helm-docs
        run: |
          helm-docs -t README.md.gotmpl -o README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        id: auto-commit
        with:
          branch: ${{ github.event.pull_request.head.ref }}
